name: brick_oven
description: Easily create & format mason brick templates with the brick_oven cli generator for mason
version: 0.1.0-dev
homepage: https://github.com/mrgnhnt96/brick_oven
repository: https://github.com/mrgnhnt96/brick_oven
issue_tracker: https://github.com/mrgnhnt96/brick_oven/issues

topics:
    - mason
    - cli
    - bricks

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.0
  autoequal: ^0.9.0
  equatable: ^2.0.5
  file: ^7.0.0
  get_it: ^7.6.6
  glob: ^2.1.2
  json_annotation: ^4.8.1
  mason_logger: ^0.2.11
  meta: ^1.9.0
  path: ^1.8.3
  pub_updater: ">=0.3.1 <0.5.0"
  watcher: ^1.0.2
  yaml: ^3.1.1

dev_dependencies:
  autoequal_gen: ^0.9.0
  build_runner: ^2.4.8
  build_version: ^2.1.1
  derry: ^1.5.0
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  mason: ^0.1.0-dev.41
  mocktail: ^1.0.2
  test: ^1.22.0
  universal_io: ^2.2.2
  very_good_analysis: ^5.1.0
  very_good_cli: ^0.19.1

executables:
  brick_oven: brick_oven

scripts: derry.yaml

import_sorter:
  comments: false
